// Deploy build: compiles ONLY MailChat's own code and leans on esm.sh for
// vendor libraries (React, supabase-js, lucide) via an import map. That keeps
// the payload the `app` edge function serves — and redeploys of it — tiny.
//
// Outputs supabase/functions/app/assets.ts with { path: content } and prints
// sizes. Usage: node scripts/build-lite.mjs

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";

const root = new URL("..", import.meta.url).pathname;
const out = `${root}dist-lite`;
mkdirSync(out, { recursive: true });

// Versions here must match package.json so dev (vite/node_modules) and prod
// (esm.sh) run identical code.
const VERSIONS = {
  react: "18.3.1",
  "react-dom": "18.3.1",
  supabase: "2.98.0",
  lucide: "0.462.0",
};

// 1. App code — esbuild with vendor left external (import map resolves it).
execFileSync(
  "npx",
  [
    "esbuild",
    "src/main.tsx",
    "--bundle",
    "--minify",
    "--format=esm",
    "--jsx=automatic",
    "--target=es2020",
    `--outfile=${out}/app.js`,
    "--external:react",
    "--external:react/jsx-runtime",
    "--external:react-dom/client",
    "--external:@supabase/supabase-js",
    "--external:lucide-react",
    "--loader:.css=empty",
    "--alias:@=./src",
  ],
  { cwd: root, stdio: "inherit" },
);

// 2. Styles — the normal Tailwind pipeline.
execFileSync("npx", ["tailwindcss", "-i", "src/index.css", "-o", `${out}/app.css`, "--minify"], {
  cwd: root,
  stdio: "inherit",
});

// 3. The page. Import map pins vendor versions; ?deps keeps one React copy.
const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💬</text></svg>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta name="robots" content="noindex" />
    <title>MailChat</title>
    <link rel="stylesheet" href="./app.css" />
    <script type="importmap">
    {
      "imports": {
        "react": "https://esm.sh/react@${VERSIONS.react}",
        "react/jsx-runtime": "https://esm.sh/react@${VERSIONS.react}/jsx-runtime",
        "react-dom/client": "https://esm.sh/react-dom@${VERSIONS["react-dom"]}/client?deps=react@${VERSIONS.react}",
        "@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@${VERSIONS.supabase}",
        "lucide-react": "https://esm.sh/lucide-react@${VERSIONS.lucide}?deps=react@${VERSIONS.react}"
      }
    }
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./app.js"></script>
  </body>
</html>
`;
writeFileSync(`${out}/index.html`, html);

// 4. Pack into the function's assets module.
const files = {
  "index.html": html,
  "app.js": readFileSync(`${out}/app.js`, "utf8"),
  "app.css": readFileSync(`${out}/app.css`, "utf8"),
};
let report = "";
for (const [name, content] of Object.entries(files)) {
  report += `  ${name}: ${Math.round(content.length / 1024)} KB\n`;
}
// The payload is gzip + base64 and lives in the app_assets_parts table —
// the app function assembles and decodes it on its first request. Loading
// goes through SQL in ~2 KB chunks; base64 contains no quotes or escape
// sequences, and each chunk's md5 can be checked after insert, so the
// payload survives being copied between tools without silent corruption.
const packed = gzipSync(Buffer.from(JSON.stringify(files), "utf8"), { level: 9 }).toString("base64");
const chunks = [];
for (let i = 0; i < packed.length; i += 1900) chunks.push(packed.slice(i, i + 1900));
const values = chunks.map((c, i) => `  (${i}, '${c}')`).join(",\n");
const sql = `-- Generated by scripts/build-lite.mjs — do not edit.
-- Loads the built frontend into app_assets_parts (run against the MailChat
-- Supabase project after any frontend change; no function redeploy needed).
begin;
delete from app_assets_parts;
insert into app_assets_parts (seq, part) values
${values};
commit;
-- Verify (expect ${createHash("md5").update(packed).digest("hex")} / ${packed.length}):
-- select md5(string_agg(part, '' order by seq)), sum(length(part)) from app_assets_parts;
`;
writeFileSync(`${root}supabase/functions/app/load-assets.sql`, sql);
report += `  packed: ${Math.round(packed.length / 1024)} KB base64 in ${chunks.length} chunks (md5 ${createHash("md5").update(packed).digest("hex")})\n`;
for (const [i, c] of chunks.entries()) {
  report += `    chunk ${i}: md5 ${createHash("md5").update(c).digest("hex")} len ${c.length}\n`;
}
console.log(report + `Wrote supabase/functions/app/load-assets.sql`);
